### ISSUE TITLE
在ubuntu16.04上编译不过啊

### ISSUE THREAD

**Issue by Bringer-of-Light** [viabtc/viabtc_exchange_server#129]
安装了所有依赖的包，accesshttp编译通过，
accessws编译错误

../libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_version':
openssl.c:(.text+0xe67): undefined reference to `SSLeay'
../libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_set_engine_default':
openssl.c:(.text+0x11c0): undefined reference to `ENGINE_set_default'
../libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_seed.part.5':
openssl.c:(.text+0x13d9): undefined reference to `RAND_file_name'
openssl.c:(.text+0x13ef): undefined reference to `RAND_load_file'
../libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_seed':
openssl.c:(.text+0x1498): undefined reference to `RAND_load_file'
../libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_step1':
openssl.c:(.text+0x23f0): undefined reference to `BIO_f_ssl'
../libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_init':
openssl.c:(.text+0x3447): undefined reference to `OPENSSL_load_builtin_modules'
../libs/libcurl.a(libcurl_la-openssl.o): In function `servercert':
openssl.c:(.text+0x3caa): undefined reference to `OCSP_response_status'
openssl.c:(.text+0x3cbd): undefined reference to `OCSP_response_status_str'
openssl.c:(.text+0x4b24): undefined reference to `OCSP_response_get1_basic'
openssl.c:(.text+0x4b5c): undefined reference to `OCSP_basic_verify'
openssl.c:(.text+0x4ba8): undefined reference to `OCSP_resp_count'
openssl.c:(.text+0x4bbe): undefined reference to `OCSP_resp_get0'
openssl.c:(.text+0x4be3): undefined reference to `OCSP_single_get0_status'
openssl.c:(.text+0x4c07): undefined reference to `OCSP_check_validity'
openssl.c:(.text+0x4c17): undefined reference to `OCSP_cert_status_str'
openssl.c:(.text+0x4e12): undefined reference to `OCSP_crl_reason_str'

matchengine也编译错误
me_persist.o: In function `get_last_slice':
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:34: undefined reference to `mysql_real_query'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:36: undefined reference to `mysql_error'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:36: undefined reference to `mysql_errno'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:36: undefined reference to `mysql_error'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:36: undefined reference to `mysql_errno'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:37: undefined reference to `mysql_error'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:37: undefined reference to `mysql_errno'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:43: undefined reference to `mysql_store_result'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:44: undefined reference to `mysql_num_rows'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:46: undefined reference to `mysql_free_result'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:50: undefined reference to `mysql_fetch_row'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:55: undefined reference to `mysql_free_result'
me_persist.o: In function `init_from_db':
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:163: undefined reference to `mysql_close'
/opt/bilala/viabtc_exchange_server/matchengine/me_persist.c:169: undefined reference to `mysql_close'
me_persist.o: In function `update_slice_history':

**Comment by ohld** [comment]
Can you please share step-by-step how to reproduce this error?

**Comment by ohld** [comment]
@Junbin-Hao See installation setup here in Readme: http://github.com/testnet-exchange/python-viab…

**Comment by Junbin-Hao** [comment]
@ohld thanks.

**Comment by Bringer-of-Light** [comment]
@ohld @Junbin-Hao 

#### 我的编译方法，请看README最后面
[https://github.com/Bringer-of-Light/viabtc_exchange_server
](https://github.com/Bringer-of-Light/viabtc_exchange_server)

- 在ubuntu 14.04x64上全部编译成功，修改了accessws的makefile，调整了-lcurl的顺序，把它放到-lssl之前
- 在ubuntu 16.04x64上matchengine及readhistory编译失败，其他的可以编译成功，错误原因看起来跟libmysqlclient及gcc有关，找不到new，delete等大量的符号，libmysqlclient是c++的项目，而viabtc是c项目，暂时未找到解决方法

#### Here is my solution, scroll down to the page end: **Build on Ubuntu14.04x64**
[https://github.com/Bringer-of-Light/viabtc_exchange_server
](https://github.com/Bringer-of-Light/viabtc_exchange_server)

- all success on ubuntu14.04x64, I have to modify the makefile of accessws, place -lcurl in front of -lssl solve the link error.
- on ubuntu16.04x64, matchengine and readhistory compile failed while all other is success. many link erros occured when compiling matchengine, such as `undefined reference to opreator new`, `undefined reference to opreator new ` and etc. looks like libmysqlclient is involved since it is a c++ project while viabtc is c project. gcc may need something more to link to a c++ lib, but I haven't found a solution.

**Comment by ohld** [comment]
@Bringer-of-Light Can you please avoid using Chinese because, if you do so, you are increasing the chance that the developers across all GitHub can not only use your code, but even fix bugs. 

My second question is why you have not used any dockerisation in your solution? This is very useful way to test and deploy the exchange on any environment. Please check the way I've done it here: 
https://github.com/testnet-exchange/viabtc_exchange_server/tree/master/docker

**Comment by Bringer-of-Light** [comment]
@ohld 
OK, I will try not to use Chinese anymore.

I'm not using docker, because it looks like that all docker repo of viabtc I found is written for test purpose, all viabtc subunit (include matchengine, accesshttp, etc.) running on the same machine, which should be avoid in production environment.
we really want to modify these docker projects to adapt into our needs, but we are not familiar with docker, and we don't have much time to learn it right now.

**Comment by Junbin-Hao** [comment]
@Bringer-of-Light 
I was able to compile all on ubuntu 16.04x64 version, do you have MySQL installed?

**Comment by ohld** [comment]
@Bringer-of-Light You can take a look at `docker-compose.yml` file in my [repo](https://github.com/testnet-exchange/viabtc_exchange_server/blob/master/docker/docker-compose.yml). There is a way to launch this set of dockers on a cluster (search for `docker swarm`). 

By default all dockers in docker-compose are run on the single node inside a virtual local net, that helps in their communication (you can see the ip-addresses in `docker-compose.yml` file).

**Comment by ohld** [comment]
@Bringer-of-Light 
I don't quite sure that you can easily duplicate services (two accesshttp in your case) with docker swarm. You need some load balancer and I don't know it `docker swarm` has it out-of-the-box. I know that `nginx` is very popular load balancer, may be you need some of this. 

But anyway. You definitely should check `Dockerfile`'s of every service and than `docker-compose.yml`which combines them. All that stuff allows be to launch the exchange server with only three commands:

``git clone https://github.com/testnet-exchange/viabtc_exchange_server
cd viabtc_exchange_server/docker
sudo docker-compose up```

**Comment by Bringer-of-Light** [comment]
@ohld
OK, I'm using load balancer. 
"docker-compose up" will make everything online, but on one single machine, which is not the best for production. 
what I'm really want to do is: I have multi machine, each one has it's own purpose. such as one for matchengine, one for marketprice, two for accesshttp, etc. after I have install docker and run "git clone" on every machine, I can not run "docker-compose up" on every machine, because "matchengine" should have only one instance. 
I'm still a little confusing. on my matchengine machine, I run "docker-compose up matchengine", on my accesshttp machine, I run "docker-compose up accesshttp". But how can these two knowing each other and work together?

I'm doing docker stuff right now, will keep you update If I can put all this together and deploy it into production. 

Thanks!

**Comment by ohld** [comment]
@Bringer-of-Light 
Take a look at `docker swarm`: https://docs.docker.com/engine/swarm/
You can join all your machines in a swarm (read the tutorial on the docker site). There is a way to deploy all dockers from  your docker-compose to your swarm so different containers will be on a different machines of a swarm:  https://docs.docker.com/engine/swarm/stack-deploy/#create-the-example-application

All your swarm machines will be united into a single virtual local network so your containers could communicate with each other in a private network.

**Comment by Bringer-of-Light** [comment]
@ohld 
I got these error on my ubuntu18 machine when using docker-compose up
```
 sudo docker-compose up

exchange_kafka is up-to-date
Starting exchange_mysql ... 
Starting exchange_mysql        ... error
exchange_cli is up-to-date

ERROR: for exchange_mysql  Cannot start service mysql: OCI runtime create failed: container_linux.go:348: starting container proces
Starting exchange_redis_master ... error

ERROR: for exchange_redis_master  Cannot start service redis-master: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied": unknown

ERROR: for mysql  Cannot start service mysql: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied": unknown

ERROR: for redis-master  Cannot start service redis-master: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
root@marketprice:/opt/bilala/viabtc_exchange_server/docker# 

```

**Comment by ohld** [comment]
I don't know this error. Do you use the latest docker and docker-compose? Try this tutorial to reinstall docker: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04

**Comment by Bringer-of-Light** [comment]
@ohld
do you know why this error is happening?

**Comment by ohld** [comment]
Actually I've had the same error on Centos. But on Ubuntu / Debian all is fine.

**Comment by lealife** [comment]
Install it on Centos: https://github.com/lealife/viabtc_exchange_server/issues/1
